// Copyright 2021 opdev.cn, Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License").
// You may not use this file except in compliance with the License.
// A copy of the License is located at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.
// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	metricsv1alpha1 "github.com/bbaobelief/k8s-falcon-metrics-adapter/pkg/apis/metrics/v1alpha1"
	versioned "github.com/bbaobelief/k8s-falcon-metrics-adapter/pkg/client/clientset/versioned"
	internalinterfaces "github.com/bbaobelief/k8s-falcon-metrics-adapter/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/bbaobelief/k8s-falcon-metrics-adapter/pkg/client/listers/metrics/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// CustomMetricInformer provides access to a shared informer and lister for
// CustomMetrics.
type CustomMetricInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.CustomMetricLister
}

type customMetricInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewCustomMetricInformer constructs a new informer for CustomMetric type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewCustomMetricInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredCustomMetricInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredCustomMetricInformer constructs a new informer for CustomMetric type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredCustomMetricInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.MetricsV1alpha1().CustomMetrics(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.MetricsV1alpha1().CustomMetrics(namespace).Watch(context.TODO(), options)
			},
		},
		&metricsv1alpha1.CustomMetric{},
		resyncPeriod,
		indexers,
	)
}

func (f *customMetricInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredCustomMetricInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *customMetricInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&metricsv1alpha1.CustomMetric{}, f.defaultInformer)
}

func (f *customMetricInformer) Lister() v1alpha1.CustomMetricLister {
	return v1alpha1.NewCustomMetricLister(f.Informer().GetIndexer())
}
